<?php

namespace Athena\IhmBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * SaveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaveRepository extends EntityRepository {

	public function weekSaves() {

	$query = 
		$this->_em
			->createQuery('
							SELECT s.day, s.month, st.displayState
							FROM AthenaIhmBundle:Save s
							INNER JOIN AthenaIhmBundle:State st
							WHERE s.state = st.id
							AND (s.day BETWEEN :dayS AND :dayE)
							AND s.month = :month
						'
						)
	;

	$query->setParameters(array(
							"dayS" => date('d')-6,
							"dayE" => date('d'),
							"month" => date('m')
						)
					)
	;

	return $query->getResult();


	}

	public function targetResto($month, $day) {

		$query = 
		$this->_em
			->createQuery('
							SELECT st.displayState
							FROM AthenaIhmBundle:Save s
							INNER JOIN AthenaIhmBundle:State st
							WHERE s.state = st.id
							AND s.month = :month
							AND s.day = :day
						'
						)
		;

		$query->setParameters(array(
								"day" => $day,
								"month" => $month
							)
						)
	;

		return $query->getResult();
	}
}
